import com.koupper.container.context
import com.koupper.octopus.annotations.Export
import java.io.File

data class Input(
    val baseBranch: String = "develop",
    val headBranch: String? = null,
    val title: String? = null,
    val body: String? = null,
    val draft: Boolean = false,
    val pushBranch: Boolean = true
)

data class CommandResult(
    val command: String,
    val exitCode: Int,
    val output: String
)

private fun runCommand(args: List<String>, cwd: File): CommandResult {
    val process = ProcessBuilder(args)
        .directory(cwd)
        .redirectErrorStream(true)
        .start()

    val output = process.inputStream.bufferedReader().readText().trim()
    val exitCode = process.waitFor()
    return CommandResult(command = args.joinToString(" "), exitCode = exitCode, output = output)
}

private fun ensureOk(result: CommandResult, step: String) {
    if (result.exitCode != 0) {
        error("$step failed (${result.command}): ${result.output}")
    }
}

private fun resolveCurrentBranch(cwd: File): String {
    val current = runCommand(listOf("git", "branch", "--show-current"), cwd)
    ensureOk(current, "resolve current branch")
    return current.output.ifBlank { error("unable to resolve current branch") }
}

private fun autoBody(cwd: File, base: String, head: String): String {
    val commits = runCommand(listOf("git", "log", "--oneline", "$base..$head"), cwd)
    ensureOk(commits, "collect commits for PR body")
    val bulletLines = commits.output
        .lines()
        .map { it.trim() }
        .filter { it.isNotBlank() }
        .take(8)
        .joinToString("\n") { "- $it" }

    val diffStat = runCommand(listOf("git", "diff", "--stat", "$base..$head"), cwd)
    ensureOk(diffStat, "collect diff stat for PR body")

    return buildString {
        appendLine("## Summary")
        if (bulletLines.isBlank()) {
            appendLine("- Automated PR generated by scripts/release/pr-create.kts")
        } else {
            appendLine(bulletLines)
        }
        appendLine()
        appendLine("## Diff")
        appendLine("```")
        appendLine(diffStat.output.ifBlank { "No file changes detected." })
        appendLine("```")
    }.trim()
}

@Export
val setup: (Input) -> Map<String, Any?> = { input ->
    val cwd = File(context ?: ".").absoluteFile
    val head = input.headBranch?.takeIf { it.isNotBlank() } ?: resolveCurrentBranch(cwd)

    if (input.pushBranch) {
        ensureOk(runCommand(listOf("git", "push", "-u", "origin", head), cwd), "push feature branch")
    }

    val computedTitle = input.title?.takeIf { it.isNotBlank() } ?: run {
        val latest = runCommand(listOf("git", "log", "-1", "--format=%s"), cwd)
        ensureOk(latest, "resolve default PR title")
        latest.output.ifBlank { "chore: update branch $head" }
    }

    val computedBody = input.body?.takeIf { it.isNotBlank() } ?: autoBody(cwd, input.baseBranch, head)

    val createArgs = mutableListOf(
        "gh", "pr", "create",
        "--base", input.baseBranch,
        "--head", head,
        "--title", computedTitle,
        "--body", computedBody
    )
    if (input.draft) createArgs += "--draft"

    val created = runCommand(createArgs, cwd)
    ensureOk(created, "create PR")

    val prUrl = created.output.lines().firstOrNull { it.startsWith("http") }
        ?: run {
            val fallback = runCommand(listOf("gh", "pr", "view", "--json", "url", "--jq", ".url"), cwd)
            ensureOk(fallback, "resolve PR URL")
            fallback.output
        }

    mapOf(
        "ok" to true,
        "baseBranch" to input.baseBranch,
        "headBranch" to head,
        "title" to computedTitle,
        "url" to prUrl
    )
}
