import com.koupper.shared.annotations.Export

/**
 * Example demonstrating Koupper v7's Server-Sent Events (SSE) Streaming.
 * When executed via `POST /api/v1/run-stream`, the standard output logs
 * generated by `println` will be streamed to the client in real-time,
 * rather than waiting for the script to finish completely to return a response.
 */
@Export
val runStreamingTest: () -> String = {
    println("[SSE Example] Iniciando trabajo de larga duración...")
    
    for (i in 1..10) {
        // En un entorno de streaming SSE, este output será enviado
        // inmediatamente al cliente con el formato text/event-stream
        println("[SSE Example] Procesando lote $i/10")
        Thread.sleep(1000)
    }

    println("[SSE Example] Trabajo finalizado con éxito.")
    
    "SUCCESS"
}
