plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'com.google.devtools.ksp' version '2.0.20-1.0.25'
}

dependencies {
    implementation "com.google.devtools.ksp:symbol-processing-api:2.0.20-1.0.25"
    implementation project(':shared')
    
    testImplementation "io.kotest:kotest-runner-junit5:5.9.1"
    testImplementation "io.kotest:kotest-assertions-core:5.9.1"
    testImplementation "io.mockk:mockk:1.13.12"
}
