plugins {
    id 'application'
    id "org.jetbrains.kotlin.jvm"
    id 'maven-publish'
}

application {
    mainClassName = 'com.koupper.shared.ExtensionsKt'
}

version = '1.0.0'
group = 'com.koupper'

dependencies {
    implementation "com.fasterxml.jackson.module:jackson-module-kotlin:2.17.0"
    implementation "com.fasterxml.jackson.core:jackson-databind:2.17.0"
    implementation "com.fasterxml.jackson.core:jackson-annotations:2.17.0"
    implementation "io.opentelemetry:opentelemetry-api:1.40.0"
    implementation "io.opentelemetry:opentelemetry-sdk:1.40.0"
    implementation "io.opentelemetry:opentelemetry-sdk-trace:1.40.0"
    implementation "io.opentelemetry:opentelemetry-exporter-logging:1.40.0"
}

jar {
    manifest {
        attributes 'Main-Class': 'com.koupper.shared.ExtensionsKt'
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
