plugins {
    id 'application'
    id "org.jetbrains.kotlin.jvm"
    id 'maven-publish'
}

application {
    mainClassName = 'com.koupper.shared.ExtensionsKt'
}

version = '1.0.0'
group = 'com.koupper'

jar {
    manifest {
        attributes 'Main-Class': 'com.koupper.shared.ExtensionsKt'
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
