/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.kup.server

import org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory
import javax.ws.rs.core.UriBuilder

fun main() {
    val url = UriBuilder.fromUri("http://localhost/")
        .port(9090)
        .build()

    val httpServer = GrizzlyHttpServerFactory.createHttpServer(
        url,
        Application(),
        true
    )

    if (System.getenv()["SHUTDOWN_TYPE"].equals("INPUT")) {
        println("Press any key to shutdown")
        readLine()
        println("Shutting down from input")
        httpServer.shutdownNow()
    } else {
        Runtime.getRuntime().addShutdownHook(Thread {
            println("Shutting down from shutdown hook")
            httpServer.shutdownNow()
        })

        println("Press Ctrl+C to shutdown")
        Thread.currentThread().join()
    }
}
